xd = input('\033[4;37mDigite algo:\033[m ')
print(type(xd))
print(xd, 'é alfanumérico?', xd.isalnum())
print(xd, 'é somente letras?', xd.isalpha())
print(xd, 'está somente em minúsculo?', xd.islower())
print(xd, 'é apenas números?', xd.isnumeric())
print(xd, 'está apenas em maíusculo?', xd.isupper())
print(xd, 'é apenas espaços? ', xd.isspace())
print(xd, 'é apenas dígitos? ', xd.isdigit())
print(xd, 'é imprimível? ', xd.isprintable())
